(()=>{'use strict';
const K='yunotsubasa_sheet_connection_v1',TTL=180*24*60*60*1000,CFG=window.YUNOTSUBASA_EDIT_CONFIG;
let birds=[],conn=null,token='',headers=[];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const FIELDS=['脚環番号','個体名','性別','羽色','作出年','作出者','父','母','父方祖父','父方祖母','母方祖父','母方祖母','競翔成績','血統・特徴','価格','状態','鳩画像URL','血統書画像URL','備考'];
function idFrom(v){const t=String(v||''),m=t.match(/\/spreadsheets\/d\/([A-Za-z0-9_-]+)/);return m?m[1]:''}
function getC(){try{const x=JSON.parse(localStorage.getItem(K)||'null');if(!x||Date.now()>x.expiresAt)return null;return x}catch{return null}}
function saveC(id,name){const x={sheetId:id,sheetName:name||'鳩データベース',expiresAt:Date.now()+TTL};localStorage.setItem(K,JSON.stringify(x));return x}
function csvURL(){return `https://docs.google.com/spreadsheets/d/${conn.sheetId}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(conn.sheetName)}&_=${Date.now()}`}
function parseCSV(t){let rs=[],r=[],c='',q=false;for(let i=0;i<t.length;i++){let ch=t[i],n=t[i+1];if(ch=='"'){if(q&&n=='"'){c+='"';i++}else q=!q}else if(ch==','&&!q){r.push(c);c=''}else if((ch=='\n'||ch=='\r')&&!q){if(ch=='\r'&&n=='\n')i++;r.push(c);rs.push(r);r=[];c=''}else c+=ch}if(c||r.length){r.push(c);rs.push(r)}return rs}
async function load(){conn=getC();if(!conn)return setup();$('#loading').hidden=false;try{const r=await fetch(csvURL(),{cache:'no-store'});const rows=parseCSV(await r.text());headers=rows.shift()||[];birds=rows.filter(x=>x.some(Boolean)).map((x,idx)=>Object.assign({_row:idx+2},Object.fromEntries(headers.map((h,i)=>[h,x[i]||'']))));$('#loading').hidden=true;render()}catch{$('#loading').hidden=true;$('#error').hidden=false;$('#error').textContent='読み込みに失敗しました。'}}
function render(){const q=$('#keyword').value.toLowerCase();const a=birds.filter(b=>Object.values(b).join(' ').toLowerCase().includes(q));$('#resultCount').textContent=`${a.length}件`;$('#birdList').innerHTML=a.map(b=>`<article class="bird"><div class="ring">${esc(b['脚環番号'])}</div><div class="name">${esc(b['個体名'])}</div><div class="meta">${esc([b['性別'],b['羽色'],b['作出年'],b['状態']].filter(Boolean).join(' ／ '))}</div><button class="edit-button" data-row="${b._row}">編集する</button></article>`).join('');document.querySelectorAll('.edit-button').forEach(x=>x.onclick=()=>openEdit(Number(x.dataset.row)))}
function field(n,v=''){const ta=['競翔成績','血統・特徴','備考'].includes(n);return `<label class="field ${ta?'wide':''}"><span>${esc(n)}</span>${ta?`<textarea name="${esc(n)}">${esc(v)}</textarea>`:`<input name="${esc(n)}" value="${esc(v)}">`}</label>`}
function openEdit(row=0){const b=row?birds.find(x=>x._row===row):{};$('#editTitle').textContent=row?'登録鳩を編集':'新規登録';$('#editForm').dataset.row=row;$('#editFields').innerHTML=`<div class="edit-grid">${FIELDS.map(n=>field(n,b?.[n]||'')).join('')}</div>`;$('#deleteButton').style.display=row?'block':'none';$('#editMessage').textContent='';$('#editModal').showModal()}
function auth(){if(!CFG.clientId||CFG.clientId.startsWith('YOUR_')){alert('Google OAuth クライアントIDが未設定です。');return}const c=google.accounts.oauth2.initTokenClient({client_id:CFG.clientId,scope:'https://www.googleapis.com/auth/spreadsheets',callback:r=>{if(r.error)return;token=r.access_token;$('#authStatus').textContent='編集可能';$('#googleLoginButton').textContent='Google認証済み'}});c.requestAccessToken({prompt:''})}
async function updateRow(row,data){const vals=headers.map(h=>data[h]??'');const end=col(headers.length);const range=`${conn.sheetName}!A${row}:${end}${row}`;const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${conn.sheetId}/values/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({values:[vals]})});if(!r.ok)throw new Error(await r.text())}
async function appendRow(data){const vals=headers.map(h=>data[h]??'');const range=`${conn.sheetName}!A:${col(headers.length)}`;const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${conn.sheetId}/values/${encodeURIComponent(range)}:append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({values:[vals]})});if(!r.ok)throw new Error(await r.text())}
async function deleteRow(row){const meta=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${conn.sheetId}?fields=sheets.properties`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json());const sh=meta.sheets.find(s=>s.properties.title===conn.sheetName);if(!sh)throw new Error('シートが見つかりません');const req={requests:[{deleteDimension:{range:{sheetId:sh.properties.sheetId,dimension:'ROWS',startIndex:row-1,endIndex:row}}}]};const r=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${conn.sheetId}:batchUpdate`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(req)});if(!r.ok)throw new Error(await r.text())}
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function setup(){$('#setupPanel').hidden=false;$('#dataPanel').hidden=true}
$('#connectButton').onclick=()=>{const id=idFrom($('#sheetUrl').value);if(!id)return $('#setupMessage').textContent='URLを確認してください。';conn=saveC(id,$('#sheetName').value.trim());$('#setupPanel').hidden=true;$('#dataPanel').hidden=false;load()}
$('#settingsButton').onclick=setup;$('#googleLoginButton').onclick=auth;$('#keyword').oninput=render;$('#newButton').onclick=()=>openEdit();$('#closeEdit').onclick=()=>$('#editModal').close();
$('#editForm').onsubmit=async e=>{e.preventDefault();if(!token)return $('#editMessage').textContent='先にGoogle認証をしてください。';const data=Object.fromEntries(new FormData(e.currentTarget).entries()),row=Number(e.currentTarget.dataset.row||0);try{$('#editMessage').textContent='保存中…';row?await updateRow(row,data):await appendRow(data);$('#editModal').close();await load()}catch(err){$('#editMessage').textContent='保存に失敗しました。';console.error(err)}}
$('#deleteButton').onclick=async()=>{const row=Number($('#editForm').dataset.row||0);if(!row||!token)return;if(!confirm('この鳩を削除しますか？'))return;try{await deleteRow(row);$('#editModal').close();await load()}catch(e){$('#editMessage').textContent='削除に失敗しました。'}}
conn=getC();if(conn){$('#setupPanel').hidden=true;$('#dataPanel').hidden=false;load()}else setup();
})();