(()=>{'use strict';
const K='yunotsubasa_sheet_connection_v1',TTL=180*24*60*60*1000;
let birds=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function idFrom(v){const t=String(v||'').trim(),m=t.match(/\/spreadsheets\/d\/([A-Za-z0-9_-]+)/);return m?m[1]:(/^[A-Za-z0-9_-]{20,}$/.test(t)?t:'')}
function getC(){try{const x=JSON.parse(localStorage.getItem(K)||'null');if(!x||!x.sheetId||Date.now()>x.expiresAt){localStorage.removeItem(K);return null}return x}catch{localStorage.removeItem(K);return null}}
function saveC(id,name){const x={sheetId:id,sheetName:name||'鳩データベース',expiresAt:Date.now()+TTL};localStorage.setItem(K,JSON.stringify(x));return x}
function csvURL(c){return `https://docs.google.com/spreadsheets/d/${encodeURIComponent(c.sheetId)}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(c.sheetName)}&_=${Date.now()}`}
function parseCSV(t){let rs=[],r=[],c='',q=false;for(let i=0;i<t.length;i++){let ch=t[i],n=t[i+1];if(ch=='"'){if(q&&n=='"'){c+='"';i++}else q=!q}else if(ch==','&&!q){r.push(c);c=''}else if((ch=='\n'||ch=='\r')&&!q){if(ch=='\r'&&n=='\n')i++;r.push(c);rs.push(r);r=[];c=''}else c+=ch}if(c||r.length){r.push(c);rs.push(r)}return rs}
function img(u){const t=String(u||''),m=t.match(/\/d\/([A-Za-z0-9_-]+)/)||t.match(/[?&]id=([A-Za-z0-9_-]+)/);return m?`https://drive.google.com/thumbnail?id=${m[1]}&sz=w1600`:t}
async function load(){const c=getC();if(!c){setup();return}$('#connectedSheet').textContent=`${c.sheetName} / ${c.sheetId}`;$('#loading').hidden=false;$('#error').hidden=true;try{const r=await fetch(csvURL(c),{cache:'no-store'});if(!r.ok)throw 0;const rows=parseCSV(await r.text()),h=rows.shift()||[];birds=rows.filter(x=>x.some(v=>String(v||'').trim())).map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]||''])));$('#loading').hidden=true;render()}catch{$('#loading').hidden=true;$('#error').hidden=false;$('#error').textContent='スプレッドシートを読み込めませんでした。URL・シート名・共有設定を確認してください。'}}
function render(){const q=$('#keyword').value.trim().toLowerCase(),sex=$('#sexFilter').value,st=$('#statusFilter').value;const a=birds.filter(b=>(!q||Object.values(b).join(' ').toLowerCase().includes(q))&&(!sex||b['性別']===sex)&&(!st||b['状態']===st));$('#resultCount').textContent=`${a.length}件`;$('#birdList').innerHTML=a.map(b=>`<article class="bird"><div class="ring">${esc(b['脚環番号'])}</div><div class="name">${esc(b['個体名'])}</div><div class="meta">${esc([b['性別'],b['羽色'],b['作出年'],b['状態']].filter(Boolean).join(' ／ '))}</div><button class="detail-button" type="button" data-ring="${esc(b['脚環番号'])}">詳細を見る</button></article>`).join('');$('#empty').hidden=!!a.length;document.querySelectorAll('.detail-button').forEach(x=>x.onclick=()=>detail(birds.find(b=>String(b['脚環番号'])===String(x.dataset.ring))))}
function detail(b){if(!b)return;const ps=[['脚環番号',b['脚環番号']],['個体名',b['個体名']],['性別',b['性別']],['羽色',b['羽色']],['作出年',b['作出年']],['作出者',b['作出者']],['父',b['父']],['母',b['母']],['父方祖父',b['父方祖父']],['父方祖母',b['父方祖母']],['母方祖父',b['母方祖父']],['母方祖母',b['母方祖母']],['競翔成績',b['競翔成績']],['血統・特徴',b['血統・特徴']],['価格',b['価格']],['状態',b['状態']],['備考',b['備考']]].filter(([,v])=>String(v||'').trim());$('#detailContent').innerHTML=`<div class="detail"><h2>${esc(b['脚環番号'])} ${esc(b['個体名'])}</h2><dl>${ps.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('')}</dl>${b['鳩画像URL']?`<h3>鳩写真</h3><img src="${esc(img(b['鳩画像URL']))}">`:''}${b['血統書画像URL']?`<h3>血統書</h3><img src="${esc(img(b['血統書画像URL']))}">`:''}</div>`;$('#detailModal').showModal()}
function setup(){const c=getC();$('#setupPanel').hidden=false;$('#dataPanel').hidden=true;if(c){$('#sheetUrl').value=`https://docs.google.com/spreadsheets/d/${c.sheetId}/edit`;$('#sheetName').value=c.sheetName}}
function data(){ $('#setupPanel').hidden=true;$('#dataPanel').hidden=false}
$('#connectButton').onclick=()=>{const id=idFrom($('#sheetUrl').value),name=$('#sheetName').value.trim()||'鳩データベース';if(!id){$('#setupMessage').textContent='GoogleスプレッドシートのURLを確認してください。';$('#setupMessage').className='message error';return}saveC(id,name);$('#setupMessage').textContent='';data();load()};
$('#settingsButton').onclick=setup;$('#reloadButton').onclick=load;['#keyword','#sexFilter','#statusFilter'].forEach(x=>$(x).oninput=render);$('#clearButton').onclick=()=>{$('#keyword').value='';$('#sexFilter').value='';$('#statusFilter').value='';render()};$('#closeModal').onclick=()=>$('#detailModal').close();
getC()?(data(),load()):setup();
})();