
const cfg=window.YUNOTSUBASA_CONFIG,grid=document.getElementById('birdGrid'),loading=document.getElementById('loading'),errorBox=document.getElementById('error'),empty=document.getElementById('empty'),count=document.getElementById('resultCount'),keyword=document.getElementById('keyword'),sexFilter=document.getElementById('sexFilter'),statusFilter=document.getElementById('statusFilter'),yearFilter=document.getElementById('yearFilter'),resetButton=document.getElementById('resetButton'),modal=document.getElementById('detailModal'),modalContent=document.getElementById('modalContent');document.getElementById('modalClose').addEventListener('click',()=>modal.close());let rows=[];
function driveImage(url){if(!url)return'';const m=String(url).match(/(?:\/d\/|id=)([-\w]{20,})/);return m?`https://drive.google.com/thumbnail?id=${m[1]}&sz=w1200`:url}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function show(v){return v!==undefined&&v!==null&&String(v).trim()!==''}
function parseGViz(text){const start=text.indexOf('{'),end=text.lastIndexOf('}'),json=JSON.parse(text.slice(start,end+1)),table=json.table,labels=table.cols.map(c=>c.label||'');return table.rows.map(r=>{const obj={};labels.forEach((label,i)=>{const cell=r.c&&r.c[i];obj[label]=cell?(cell.f??cell.v??''):''});return obj})}
async function loadData(){const url=`https://docs.google.com/spreadsheets/d/${cfg.sheetId}/gviz/tq?tqx=out:json&sheet=${encodeURIComponent(cfg.sheetName)}`;try{const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('HTTP '+res.status);rows=parseGViz(await res.text()).filter(r=>show(r['脚環番号'])||show(r['個体名']));[...new Set(rows.map(r=>String(r['作出年']||'').trim()).filter(Boolean))].sort().reverse().forEach(y=>{const o=document.createElement('option');o.value=y;o.textContent=y;yearFilter.appendChild(o)});loading.hidden=true;render()}catch(e){console.error(e);loading.hidden=true;errorBox.hidden=false;count.textContent='読み込みエラー'}}
function filteredRows(){const q=keyword.value.trim().toLowerCase();return rows.filter(r=>{const hay=['脚環番号','個体名','血統・特徴','競翔成績','父','母','作出者'].map(k=>String(r[k]||'').toLowerCase()).join(' ');return(!q||hay.includes(q))&&(!sexFilter.value||String(r['性別'])===sexFilter.value)&&(!statusFilter.value||String(r['状態'])===statusFilter.value)&&(!yearFilter.value||String(r['作出年'])===yearFilter.value)})}
function render(){const list=filteredRows();count.textContent=`${list.length}羽を表示`;grid.innerHTML='';empty.hidden=list.length!==0;list.forEach(r=>{const photo=driveImage(r['鳩画像URL']),card=document.createElement('article');card.className='bird-card';card.innerHTML=`<button type="button" data-index="${rows.indexOf(r)}"><div class="photo">${photo?`<img src="${esc(photo)}" alt="${esc(r['脚環番号']||r['個体名']||'鳩の写真')}" loading="lazy">`:`<span class="no-photo">NO PHOTO</span>`}${show(r['状態'])?`<span class="status" data-status="${esc(r['状態'])}">${esc(r['状態'])}</span>`:''}</div><div class="card-body"><div class="ring">${esc(r['脚環番号']||'脚環番号未登録')}</div>${show(r['個体名'])?`<div class="card-title">${esc(r['個体名'])}</div>`:''}<div class="card-meta">${show(r['性別'])?`<span class="tag">${esc(r['性別'])}</span>`:''}${show(r['羽色'])?`<span class="tag">${esc(r['羽色'])}</span>`:''}${show(r['作出年'])?`<span class="tag">${esc(r['作出年'])}年</span>`:''}</div>${show(r['競翔成績'])?`<p class="card-result">${esc(r['競翔成績'])}</p>`:''}${show(r['価格'])?`<div class="card-price">${esc(r['価格'])}</div>`:''}<span class="more">詳細を見る →</span></div></button>`;grid.appendChild(card)});grid.querySelectorAll('button[data-index]').forEach(b=>b.addEventListener('click',()=>openDetail(rows[Number(b.dataset.index)])))}
function row(label,value){return show(value)?`<div class="detail-row"><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`:''}
function openDetail(r){const photo=driveImage(r['鳩画像URL']),pedigree=driveImage(r['血統書画像URL']);modalContent.innerHTML=`<div class="modal-wrap"><div class="modal-head"><div class="modal-photo">${photo?`<img src="${esc(photo)}" alt="${esc(r['脚環番号']||'鳩の写真')}">`:`<span class="no-photo">NO PHOTO</span>`}</div><div><div class="modal-ring">${esc(r['脚環番号']||'脚環番号未登録')}</div>${show(r['個体名'])?`<div class="modal-name">${esc(r['個体名'])}</div>`:''}<div class="card-meta">${show(r['性別'])?`<span class="tag">${esc(r['性別'])}</span>`:''}${show(r['羽色'])?`<span class="tag">${esc(r['羽色'])}</span>`:''}${show(r['作出年'])?`<span class="tag">${esc(r['作出年'])}年</span>`:''}${show(r['状態'])?`<span class="tag">${esc(r['状態'])}</span>`:''}</div>${show(r['価格'])?`<div class="modal-price">${esc(r['価格'])}</div>`:''}</div></div><dl class="detail-table">${row('作出者',r['作出者'])}${row('父',r['父'])}${row('母',r['母'])}${row('父方祖父',r['父方祖父'])}${row('父方祖母',r['父方祖母'])}${row('母方祖父',r['母方祖父'])}${row('母方祖母',r['母方祖母'])}${row('競翔成績',r['競翔成績'])}${row('血統・特徴',r['血統・特徴'])}${row('備考',r['備考'])}</dl>${pedigree?`<div class="pedigree-image"><h3>血統書</h3><a href="${esc(pedigree)}" target="_blank" rel="noopener"><img src="${esc(pedigree)}" alt="血統書画像"></a></div>`:''}</div>`;modal.showModal()}
[keyword,sexFilter,statusFilter,yearFilter].forEach(el=>el.addEventListener('input',render));resetButton.addEventListener('click',()=>{keyword.value='';sexFilter.value='';statusFilter.value='';yearFilter.value='';render()});modal.addEventListener('click',e=>{const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close()});loadData();
